apiVersion: v1
kind: Namespace
metadata:
  name: dex

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: diego

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: staging

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: production
