{{- $argoClientSecret := include "diego-base.clientSecret" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: diego-api
  namespace: diego
type: Opaque
stringData:
  ARGOCD_API: "https://argocd.diego.{{ required "Missing .Values.domain" .Values.domain }}"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: {{ index .Values "argo-cd.configs.argocdServerAdminPassword" }}
  GITHUB_REPO_OWNER: {{ required "Missing .Values.github.orgName" .Values.github.orgName }}
  GITHUB_REPO_NAME: {{ required "Missing .Values.github.repoName" .Values.github.repoName }}
  GIN_MODE: release

---

apiVersion: v1
kind: Secret
metadata:
  name: github-app
  namespace: diego
type: Opaque
stringData:
  app_id: {{ required "Missing .Values.github.appInstallId" .Values.github.appId | quote }}
  installation_id: {{ required "Missing .Values.github.appInstallId" .Values.github.appInstallId | quote }}
  org_name: {{ required "Missing .Values.github.orgName" .Values.github.orgName }}
  app.pem: | 
{{ required "Missing .Values.github.appPemKey" .Values.github.appPemKey | indent 4 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: dex-github-oauth
  namespace: dex
type: Opaque
stringData:
  client_id: {{ required "Missing .Values.dex.clientId" .Values.dex.clientId | quote }}
  client_secret: {{ required "Missing .Values.dex.clientSecret" .Values.dex.clientSecret | quote }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: dex-static-clients-oauth
  namespace: dex
type: Opaque
stringData:
  argocd_client_secret:  {{ $argoClientSecret | quote}}
 
---
 
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc
  namespace: argocd
type: Opaque
data:
  client_secret: {{ $argoClientSecret | b64enc | quote }}