{{- $argoClientSecret := include "diego-base.clientSecret" . -}}
{{- $oauth2ProxyClientSecret := include "diego-base.clientSecret" . -}}
     
apiVersion: v1
kind: Secret
metadata:
  name: diego-api
  namespace: diego
type: Opaque
stringData:
  ARGOCD_API: "https://argocd.diego.{{ required "Missing .Values.domain" .Values.domain }}"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: {{ index .Values "argo-cd" "configs" "secret" "argocdServerAdminPassword" }}
  GITHUB_REPO_OWNER: {{ required "Missing .Values.github.orgName" .Values.github.orgName }}
  GITHUB_REPO_NAME: {{ required "Missing .Values.github.repoName" .Values.github.repoName }}
  GIN_MODE: release

---

apiVersion: v1
kind: Secret
metadata:
  name: github-app
  namespace: diego
type: Opaque
stringData:
  app_id: {{ required "Missing .Values.github.appInstallId" .Values.github.appId | quote }}
  installation_id: {{ required "Missing .Values.github.appInstallId" .Values.github.appInstallId | quote }}
  org_name: {{ required "Missing .Values.github.orgName" .Values.github.orgName }}
  app.pem: | 
{{ required "Missing .Values.github.appPemKey" .Values.github.appPemKey | indent 4 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: dex-oauth
  namespace: dex
type: Opaque
stringData:
  client_id: {{ required "Missing .Values.dex.clientId" .Values.dex.clientId | quote }}
  client_secret: {{ required "Missing .Values.dex.clientSecret" .Values.dex.clientSecret | quote }}
  argocd_client_secret:  {{ $argoClientSecret | quote }}
  oauth2_proxy_client_secret: {{ $oauth2ProxyClientSecret | quote }}

--- 
 
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oauth
  namespace: argocd
type: Opaque
data:
  client_secret: {{ $argoClientSecret | b64enc | quote }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: diego-oauth2-proxy-oauth
  namespace: diego
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 16 | nospace | b64enc | quote }}
  client-secret: {{ $oauth2ProxyClientSecret | b64enc | quote }}
  client-id: {{ "oauth2-proxy" | b64enc | quote }}