# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diego-application-viewer-role
rules:
- apiGroups:
  - management.diegocloud.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - management.diegocloud.io
  resources:
  - applications/status
  verbs:
  - get
---
# permissions for end users to createa and manage environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diego-environment-manager-role
rules:
- apiGroups:
  - management.diegocloud.io
  resources:
  - environments
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - management.diegocloud.io
  resources:
  - environments/status
  verbs:
  - get
  