apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diego-api-application-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diego-application-viewer-role
subjects:
- kind: ServiceAccount
  name: diego-api
  namespace: {{ .Release.Namespace }}
