apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diego-api-application-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-viewer
subjects:
- kind: ServiceAccount
  name: {{ .Values.diego_api.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
