apiVersion: v1
kind: Service
metadata:
  name: diego-hub-webservice
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: diego-hub
    app.kubernetes.io/name: webservice
  sessionAffinity: None
  type: NodePort