apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list