# Default values for diego-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


####### heed this warning...
# WARNING: this will emit CRDs as standard templates
# it is intended as a convenience for one-installation-per-cluster
# if you are deploying this more than once per cluster, then there will be conflicts
diego_application_controller_crds:
  enabled: false

# likewise, the following is per-cluster, so should only ever be managed at a single level.
diego_application_controller_webhooks:
  enabled: false

# # set priority class
# priorityClassName: 

diego_hub:
  image:
    repository: diegocloudio/diego-hub
    tag: main
    imagePullPolicy: Always    

diegoapi:
  # host: diego-api.core.example.com
  # aws_diego_api_role_arn: # e.g. arn:aws:iam::1234567890:role/DiegoApiRole
  image:
    repository: diegocloudio/diego-api
    tag: 0.1.0
    imagePullPolicy: Always
  ingress:
    enabled: false    

diego_application_controller:
  # project_repo_name: diego-default-project
  ingress_host_domain: example.com
  # aws_actions_role_arn: # e.g. arn:aws:iam::1234567890:role/DiegoCIRole
  # aws_diego_app_controller_role_arn: # e.g. arn:aws:iam::1234567890:role/DiegoAppControllerRole
  # aws_region: # e.g. eu-west-2
  # target_cluster_name: my-cluster
  image:
    repository: diegocloudio/application-controller
    tag: 0.1.0
