# Default values for diego-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

####### heed this warning...
# WARNING: this will emit CRDs as standard templates
# it is intended as a convenience for one-installation-per-cluster
# if you are deploying this more than once per cluster, then there will be conflicts
diego_application_controller_crds:
  enabled: false

diego_api:
  serviceAccount:
    create: true
    name: "diego-api"
  image:
    repository: diegocloudio/diego-api
    tag: main
  
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 20
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 20

  containerPort: 8080
  service:
    type: NodePort
    port: 8080

diego_application_controller:
  enabled: true
  image:
    repository: diegocloudio/application-controller
    tag: main
