{{- if .Values.diego_application_controller_webhooks.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: diego-application-controller-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - diego-application-controller-webhook-service.{{ .Release.Namespace }}.svc
  - diego-application-controller-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: diego-application-controller-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: diego-application-controller-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end -}}