apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diego-application-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diego-application-manager-role
subjects:
- kind: ServiceAccount
  name: diego-application-controller-manager
  namespace: {{ .Release.Namespace }}
