---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: diego-application-manager-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - versions/finalizers
  verbs:
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - versions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - approvals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - approvals/finalizers
  verbs:
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - approvals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - environments/finalizers
  verbs:
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - previewenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.diegocloud.io
  resources:
  - previewenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - management.diegocloud.io
  resources:
  - previewenvironments/status
  verbs:
  - get
  - patch
  - update
