apiVersion: v1
kind: ServiceAccount
metadata:
  name: diego-application-controller-manager
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.diego_application_controller.aws_diego_app_controller_role_arn | quote }}
