apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configs.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10' 
data:
{{- range $key , $val := .Values.env }}
{{- if (ne $val.value nil) }}
  {{ $key }}: {{ $val.value | quote }}
{{- end}}
{{- end}}