apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configs.name" . }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: '-1000'
data:
{{- range $key , $val := .Values.env }}
{{- if and (ne $val.value "") (ne $val.value nil) }}
  {{ $key }}: {{ $val.value | quote }}
{{- end}}
{{- end}}