apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if or .Values.env.config .Values.env.secrets .Values.env.externalSecrets }}
          envFrom:
          {{- if .Values.env.config }}
          - configMapRef:
              name: {{ include "webservice.fullname" . }}
          {{- end}}
          {{- if .Values.env.secrets }}
          - secretRef:
              name: {{ include "webservice.fullname" . }}
          {{- end}}
          {{- end}}
          env:
          {{- if .Values.env.externalSecrets }}
          {{- range $secretName, $val := .Values.env.externalSecrets }}
          {{- range $envVar, $secretKey := $val.envMapping }}
          - name: {{ $envVar }}
            valueFrom:
              secretKeyRef:
                name: {{ include "webservice.fullname" $ }}-{{ $secretName }}
                key: {{ $secretKey }}
          {{- end}}
          {{- end}}
          {{- end}}
          {{- if .Values.env.defaultSets.otelCollectorAgent.enabled }}
          - name: OTEL_COLLECTOR_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_COLLECTOR_PORT_HTTP
            value: "4318"
          - name: OTEL_COLLECTOR_PORT_GRPC
            value: "4317"
          {{- end}}
          {{- if .Values.env.defaultSets.jaegerDaemonsetAgent.enabled }}
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_AGENT_PORT
            value: {{ .Values.env.defaultSets.jaegerDaemonsetAgent.port | quote }}
          {{- end}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
