apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "configs.name" . }}
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    deletionPolicy: Delete
  data:
{{- range $key , $val := .Values.env }}
{{- if and (ne $val.secretPath "") (ne $val.secretPath nil) }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $val.secretPath }}
{{- end}}
{{- end}}