{{- range $key , $val := .Values.env.externalSecrets }}
---
apiVersion: "kubernetes-client.io/v1"
kind: "ExternalSecret"
metadata:
  name: {{ include "webservice.fullname" $ }}-{{ $key }}
spec:
{{ $val.spec | toYaml | indent 2 }}
{{- end}}