apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "configs.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10' 
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    deletionPolicy: Delete
  data:
{{- range $key , $val := .Values.env }}
{{- if (ne $val.secretPath nil) }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $val.secretPath | quote }}      
{{- if (ne $val.version nil) }} 
      version: {{ $val.version | quote }}      
{{- end}}
{{- end}}
{{- end}}