{{- range $key , $val := .Values.env.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "webservice.fullname" $ }}-{{ $key }}
spec:
{{ $val.spec | toYaml | indent 2 }}
{{- end}}