{{- range $hookName, $hookDefinition := .Values.hooks -}}
{{- if $hookDefinition -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: '{{ $hookDefinition.wave }}'
spec:
  ttlSecondsAfterFinished: 7200
  template:
    spec:
      containers:
      - name: main
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        command: {{ $hookDefinition.command | toJson }}
        envFrom:
        - configMapRef:
            name: {{ include "configs.name" $ }}
        - secretRef:
            name: {{ include "configs.name" $ }}
      restartPolicy: Never
  backoffLimit: 6
{{ end }}
{{ end }}