{{- range $hookName, $hookDefinition := .Values.hooks -}}
{{- if $hookDefinition -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  annotations:
    argocd.argoproj.io/hook: {{ $hookDefinition.phase }}
    argocd.argoproj.io/sync-wave: '{{ $hookDefinition.wave }}'
{{- if $hookDefinition.hookDeletePolicy  }} 
    argocd.argoproj.io/hook-delete-policy: {{ $hookDefinition.hookDeletePolicy }}
{{- end }}    
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: main
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        command: {{ $hookDefinition.command | toJson }}
        envFrom:
        - configMapRef:
            name: {{ include "configs.name" $ }}
      restartPolicy: Never
  backoffLimit: 6
{{ end }}
{{ end }}