{{- range $phase, $hooks := .Values.hooks -}}
{{- range $hook := $hooks -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hook.name }}
  annotations:
    argocd.argoproj.io/hook: {{ $phase }}
    argocd.argoproj.io/sync-wave: "{{ $hook.wave }}" 
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: main
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        command: {{ $hook.command | toJson }}
{{- if $.Values.env.config}}
        envFrom:
        - configMapRef:
            name: {{ include "webservice.fullname" $ }}
{{- end}}
      restartPolicy: Never
  backoffLimit: 6
{{ end }}
{{ end }}